package com.timeslot.common.api;

public enum ErrorCode {
    SUCCESS,
    VALIDATION_ERROR,
    UNAUTHORIZED,
    FORBIDDEN,
    RESOURCE_NOT_FOUND,
    ROOM_UNAVAILABLE,
    ROOM_CAPACITY_EXCEEDED,
    RESERVATION_TIME_CONFLICT,
    RESERVATION_INVALID_STATE,
    DUPLICATE_REQUEST,
    INTERNAL_ERROR
}
